services:
  elasticsearch:
    image: ${ES_DOCKER_ELASTICSEARCH_IMAGE}
    container_name: ${ES_DOCKER_ELASTICSEARCH_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${ES_DOCKER_HTTP_PORT}:9200"
      - "${ES_DOCKER_TRANSPORT_PORT}:9300"
    volumes:
      - ${ES_DOCKER_DATA_DIR_1}:/usr/share/elasticsearch/data1
      - ${ES_DOCKER_DATA_DIR_2}:/usr/share/elasticsearch/data2
      - ${ES_DOCKER_LOG_DIR}:/usr/share/elasticsearch/logs
      - ./elasticsearch/elasticsearch.generated.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      ELASTIC_PASSWORD: ${ES_DOCKER_ELASTIC_PASSWORD}
      ES_JAVA_OPTS: ${ES_DOCKER_JAVA_OPTS}

  kibana:
    image: ${ES_DOCKER_KIBANA_IMAGE}
    container_name: ${ES_DOCKER_KIBANA_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./kibana/kibana.generated.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - "${ES_DOCKER_KIBANA_PORT}:5601"

  elasticsearch-exporter:
    image: ${ES_DOCKER_EXPORTER_IMAGE}
    container_name: ${ES_DOCKER_EXPORTER_CONTAINER_NAME}
    command:
      - --es.uri=http://elastic:${ES_DOCKER_ELASTIC_PASSWORD}@elasticsearch:9200
    restart: unless-stopped
    ports:
      - "${ES_DOCKER_EXPORTER_PORT}:9114"
