# A Record
  local-data: "${UNBOUND_LOCAL_RECORD_1_FQDN}. A ${UNBOUND_LOCAL_RECORD_1_IP}"
  local-data: "${UNBOUND_LOCAL_RECORD_2_FQDN}. A ${UNBOUND_LOCAL_RECORD_2_IP}"

# PTR Record
  local-data-ptr: "${UNBOUND_LOCAL_RECORD_1_IP} ${UNBOUND_LOCAL_RECORD_1_FQDN}"
  local-data-ptr: "${UNBOUND_LOCAL_RECORD_2_IP} ${UNBOUND_LOCAL_RECORD_2_FQDN}"
