forward-zone:
    name: .
    forward-addr: ${UNBOUND_FORWARD_ADDR_1}
    forward-addr: ${UNBOUND_FORWARD_ADDR_2}
    forward-addr: ${UNBOUND_FORWARD_ADDR_3}
    forward-addr: ${UNBOUND_FORWARD_ADDR_4}
