global:
  scrape_interval:     15s
  external_labels:
    monitor: '${PROMETHEUS_EXTERNAL_LABEL}'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ${PROMETHEUS_NODE_TARGETS}

  - job_name: 'elasticsearch'
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ${PROMETHEUS_ELASTICSEARCH_TARGETS}

  - job_name: 'myna'
    scrape_interval: 30s
    static_configs:
      - targets: ${PROMETHEUS_APP_TARGETS}
