services:
  node-exporter:
    image: ${NODE_EXPORTER_IMAGE}
    container_name: ${NODE_EXPORTER_CONTAINER_NAME}
    hostname: ${NODE_EXPORTER_HOSTNAME}
    restart: unless-stopped
    volumes:
      - /:/host:ro
    command:
      - --path.rootfs=/host
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
