#!/usr/bin/env bash
#
# 部署 `db/` 目录下的聚合数据库栈。
# 这个包装脚本会先渲染模板配置，再校验并启动 compose，
# 确保 Prometheus / Kibana 读取的是生成文件而不是原始模板。

set -euo pipefail

SERVICE_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=sh/lib/common.sh
source "${SERVICE_DIR}/../sh/lib/common.sh"

# help 保持简洁，通常运维会在填写密钥前先看一眼这里。
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage_header
  echo
  echo "Render db templates and deploy the stack defined in docker-compose.yml."
  exit 0
fi

load_standard_env "${SERVICE_DIR}"

# 把镜像、端口、目录和资源限制等非敏感默认值内联到部署入口，
# 这样 .env.example 只保留账号和密钥相关变量。
: "${GLOBAL_TIMEZONE:=Asia/Shanghai}"

: "${TSDB_IMAGE:=timescale/timescaledb:2.16.1-pg16}"
: "${TSDB_CONTAINER_NAME:=tsdb}"
: "${TSDB_SHM_SIZE:=1gb}"
: "${TSDB_PRIMARY_DB:=timeseries}"
: "${TSDB_EXTRA_DATABASES:=n8n,mattermost,keycloak,openmetadata_db}"
: "${TSDB_PORT:=5433}"
: "${TSDB_DATA_DIR:=./timescaledb/data}"
: "${TSDB_SHARED_BUFFERS:=2GB}"
: "${TSDB_EFFECTIVE_CACHE_SIZE:=4GB}"
: "${TSDB_WORK_MEM:=32MB}"
: "${TSDB_MAINTENANCE_WORK_MEM:=512MB}"
: "${TSDB_MAX_CONNECTIONS:=200}"
: "${TSDB_MAX_PARALLEL_WORKERS:=8}"
: "${TSDB_MAX_PARALLEL_WORKERS_PER_GATHER:=4}"
: "${TSDB_MEM_LIMIT:=7g}"
: "${TSDB_MEM_RESERVATION:=2g}"

: "${PGADMIN_IMAGE:=dpage/pgadmin4:9.10}"
: "${PGADMIN_CONTAINER_NAME:=pgadmin}"
: "${PGADMIN_EMAIL:=admin@example.com}"
: "${PGADMIN_INTERNAL_PORT:=80}"
: "${PGADMIN_PORT:=8080}"
: "${PGADMIN_DATA_DIR:=./pgadmin/data}"
: "${PGADMIN_MEM_LIMIT:=768m}"
: "${PGADMIN_MEM_RESERVATION:=256m}"

: "${POSTGRES_EXPORTER_IMAGE:=prometheuscommunity/postgres-exporter:v0.16.0}"
: "${POSTGRES_EXPORTER_CONTAINER_NAME:=tsdb-exporter}"
: "${POSTGRES_EXPORTER_PORT:=9188}"
: "${POSTGRES_EXPORTER_MEM_LIMIT:=256m}"
: "${POSTGRES_EXPORTER_MEM_RESERVATION:=128m}"

: "${DB_ELASTICSEARCH_IMAGE:=docker.elastic.co/elasticsearch/elasticsearch:9.2.2}"
: "${DB_ELASTICSEARCH_CONTAINER_NAME:=elasticsearch}"
: "${DB_ELASTICSEARCH_CLUSTER_NAME:=es-node}"
: "${DB_ELASTICSEARCH_NODE_NAME:=node-1}"
: "${DB_ELASTICSEARCH_JAVA_OPTS:=-Xms2g -Xmx4g}"
: "${DB_ELASTICSEARCH_HTTP_PORT:=9200}"
: "${DB_ELASTICSEARCH_DATA_DIR:=./elasticsearch/data}"
: "${DB_ELASTICSEARCH_LOG_DIR:=./elasticsearch/log}"
: "${DB_ELASTICSEARCH_MEM_LIMIT:=4g}"
: "${DB_ELASTICSEARCH_MEM_RESERVATION:=2g}"

: "${DB_KIBANA_IMAGE:=docker.elastic.co/kibana/kibana:9.2.2}"
: "${DB_KIBANA_CONTAINER_NAME:=kibana}"
: "${DB_KIBANA_SERVER_NAME:=kibana}"
: "${DB_KIBANA_PORT:=5601}"
: "${DB_KIBANA_BASE_PATH:=/kibana}"
: "${DB_KIBANA_ENCRYPTION_KEY:=change-me-32-chars-minimum-123456}"
: "${DB_KIBANA_DATA_DIR:=./elasticsearch/kibana_data}"
: "${DB_KIBANA_MEM_LIMIT:=1g}"
: "${DB_KIBANA_MEM_RESERVATION:=512m}"

: "${DB_ELASTICSEARCH_EXPORTER_IMAGE:=prometheuscommunity/elasticsearch-exporter:v1.9.0}"
: "${DB_ELASTICSEARCH_EXPORTER_CONTAINER_NAME:=elasticsearch-exporter}"
: "${DB_ELASTICSEARCH_EXPORTER_PORT:=9114}"
: "${DB_ELASTICSEARCH_EXPORTER_MEM_LIMIT:=128m}"
: "${DB_ELASTICSEARCH_EXPORTER_MEM_RESERVATION:=64m}"

: "${MONGODB_IMAGE:=mongo:7.0.21}"
: "${MONGODB_CONTAINER_NAME:=mongo}"
: "${MONGODB_PORT:=27017}"
: "${MONGODB_DATA_DIR:=./mongo/data}"
: "${MONGODB_MEM_LIMIT:=1g}"
: "${MONGODB_MEM_RESERVATION:=512m}"

: "${MONGODB_EXPORTER_IMAGE:=percona/mongodb_exporter:0.40}"
: "${MONGODB_EXPORTER_CONTAINER_NAME:=mongo-exporter}"
: "${MONGODB_EXPORTER_PORT:=9216}"
: "${MONGODB_EXPORTER_MEM_LIMIT:=256m}"
: "${MONGODB_EXPORTER_MEM_RESERVATION:=128m}"

: "${MONGO_EXPRESS_IMAGE:=mongo-express:1.0.2}"
: "${MONGO_EXPRESS_CONTAINER_NAME:=mongo-express}"
: "${MONGO_EXPRESS_WEB_USER:=admin}"
: "${MONGO_EXPRESS_PORT:=8081}"
: "${MONGO_EXPRESS_MEM_LIMIT:=256m}"
: "${MONGO_EXPRESS_MEM_RESERVATION:=128m}"

: "${QDRANT_IMAGE:=qdrant/qdrant:v1.15.5}"
: "${QDRANT_CONTAINER_NAME:=qdrant}"
: "${QDRANT_HTTP_INTERNAL_PORT:=6333}"
: "${QDRANT_GRPC_INTERNAL_PORT:=6334}"
: "${QDRANT_HTTP_PORT:=6333}"
: "${QDRANT_GRPC_PORT:=6334}"
: "${QDRANT_DATA_DIR:=./qdrant/data}"
: "${QDRANT_MEM_LIMIT:=2g}"
: "${QDRANT_MEM_RESERVATION:=1g}"

: "${DB_PROMETHEUS_IMAGE:=prom/prometheus:v2.54.1}"
: "${DB_PROMETHEUS_CONTAINER_NAME:=prometheus}"
: "${DB_PROMETHEUS_RUN_AS:=1000:1000}"
: "${DB_PROMETHEUS_PORT:=9090}"
: "${DB_PROMETHEUS_DATA_DIR:=./prometheus/data}"
: "${DB_PROMETHEUS_RETENTION:=30d}"
: "${DB_PROMETHEUS_LOG_LEVEL:=info}"
: "${DB_PROMETHEUS_MEM_LIMIT:=512m}"
: "${DB_PROMETHEUS_MEM_RESERVATION:=256m}"
: "${DB_PROMETHEUS_REDIS_TARGETS:=[]}"
: "${DB_PROMETHEUS_MINIO_TARGETS:=[]}"
: "${DB_PROMETHEUS_NODE_TARGETS:=[]}"

: "${DB_GRAFANA_IMAGE:=grafana/grafana:11.2.2}"
: "${DB_GRAFANA_CONTAINER_NAME:=grafana}"
: "${DB_GRAFANA_RUN_AS:=472:472}"
: "${DB_GRAFANA_PORT:=3000}"
: "${DB_GRAFANA_ANONYMOUS_ENABLED:=true}"
: "${DB_GRAFANA_MEM_LIMIT:=512m}"
: "${DB_GRAFANA_MEM_RESERVATION:=256m}"
: "${GF_ADMIN_USER:=admin}"

export GLOBAL_TIMEZONE
export TSDB_IMAGE TSDB_CONTAINER_NAME TSDB_SHM_SIZE TSDB_PRIMARY_DB TSDB_EXTRA_DATABASES TSDB_PORT
export TSDB_DATA_DIR TSDB_SHARED_BUFFERS TSDB_EFFECTIVE_CACHE_SIZE TSDB_WORK_MEM
export TSDB_MAINTENANCE_WORK_MEM TSDB_MAX_CONNECTIONS TSDB_MAX_PARALLEL_WORKERS
export TSDB_MAX_PARALLEL_WORKERS_PER_GATHER TSDB_MEM_LIMIT TSDB_MEM_RESERVATION
export PGADMIN_IMAGE PGADMIN_CONTAINER_NAME PGADMIN_EMAIL PGADMIN_INTERNAL_PORT PGADMIN_PORT
export PGADMIN_DATA_DIR PGADMIN_MEM_LIMIT PGADMIN_MEM_RESERVATION
export POSTGRES_EXPORTER_IMAGE POSTGRES_EXPORTER_CONTAINER_NAME POSTGRES_EXPORTER_PORT
export POSTGRES_EXPORTER_MEM_LIMIT POSTGRES_EXPORTER_MEM_RESERVATION
export DB_ELASTICSEARCH_IMAGE DB_ELASTICSEARCH_CONTAINER_NAME DB_ELASTICSEARCH_CLUSTER_NAME
export DB_ELASTICSEARCH_NODE_NAME DB_ELASTICSEARCH_JAVA_OPTS DB_ELASTICSEARCH_HTTP_PORT
export DB_ELASTICSEARCH_DATA_DIR DB_ELASTICSEARCH_LOG_DIR DB_ELASTICSEARCH_MEM_LIMIT
export DB_ELASTICSEARCH_MEM_RESERVATION
export DB_KIBANA_IMAGE DB_KIBANA_CONTAINER_NAME DB_KIBANA_SERVER_NAME DB_KIBANA_PORT
export DB_KIBANA_BASE_PATH DB_KIBANA_ENCRYPTION_KEY DB_KIBANA_DATA_DIR DB_KIBANA_MEM_LIMIT
export DB_KIBANA_MEM_RESERVATION
export DB_ELASTICSEARCH_EXPORTER_IMAGE DB_ELASTICSEARCH_EXPORTER_CONTAINER_NAME
export DB_ELASTICSEARCH_EXPORTER_PORT DB_ELASTICSEARCH_EXPORTER_MEM_LIMIT
export DB_ELASTICSEARCH_EXPORTER_MEM_RESERVATION
export MONGODB_IMAGE MONGODB_CONTAINER_NAME MONGODB_PORT MONGODB_DATA_DIR
export MONGODB_MEM_LIMIT MONGODB_MEM_RESERVATION
export MONGODB_EXPORTER_IMAGE MONGODB_EXPORTER_CONTAINER_NAME MONGODB_EXPORTER_PORT
export MONGODB_EXPORTER_MEM_LIMIT MONGODB_EXPORTER_MEM_RESERVATION
export MONGO_EXPRESS_IMAGE MONGO_EXPRESS_CONTAINER_NAME MONGO_EXPRESS_WEB_USER MONGO_EXPRESS_PORT
export MONGO_EXPRESS_MEM_LIMIT MONGO_EXPRESS_MEM_RESERVATION
export QDRANT_IMAGE QDRANT_CONTAINER_NAME QDRANT_HTTP_INTERNAL_PORT QDRANT_GRPC_INTERNAL_PORT
export QDRANT_HTTP_PORT QDRANT_GRPC_PORT QDRANT_DATA_DIR QDRANT_MEM_LIMIT QDRANT_MEM_RESERVATION
export DB_PROMETHEUS_IMAGE DB_PROMETHEUS_CONTAINER_NAME DB_PROMETHEUS_RUN_AS DB_PROMETHEUS_PORT
export DB_PROMETHEUS_DATA_DIR DB_PROMETHEUS_RETENTION DB_PROMETHEUS_LOG_LEVEL
export DB_PROMETHEUS_MEM_LIMIT DB_PROMETHEUS_MEM_RESERVATION DB_PROMETHEUS_REDIS_TARGETS
export DB_PROMETHEUS_MINIO_TARGETS DB_PROMETHEUS_NODE_TARGETS
export DB_GRAFANA_IMAGE DB_GRAFANA_CONTAINER_NAME DB_GRAFANA_RUN_AS DB_GRAFANA_PORT
export DB_GRAFANA_ANONYMOUS_ENABLED DB_GRAFANA_MEM_LIMIT DB_GRAFANA_MEM_RESERVATION
export GF_ADMIN_USER

# 在渲染任何文件之前，先校验整套栈依赖的密钥变量。
ensure_value DB_USER
ensure_value DB_PASSWORD
ensure_value DB_ELASTIC_PASSWORD
ensure_value PGADMIN_PASSWORD
ensure_value GF_ADMIN_PASSWORD
ensure_value QDRANT_API_KEY
ensure_value MONGO_EXPRESS_WEB_PASSWORD

# 渲染那些会被 bind mount 进容器、且内部带 env 占位符的配置文件。
render_template "${SERVICE_DIR}/prometheus/prometheus.yml" "${SERVICE_DIR}/prometheus/prometheus.generated.yml"
render_template "${SERVICE_DIR}/elasticsearch/elasticsearch.yml" "${SERVICE_DIR}/elasticsearch/elasticsearch.generated.yml"
render_template "${SERVICE_DIR}/elasticsearch/kibana.yml" "${SERVICE_DIR}/elasticsearch/kibana.generated.yml"

# 模板准备完成后再启动整套服务。
run_compose_stack "${SERVICE_DIR}" "docker-compose.yml"
